/**
 * بنك الأسئلة — 112 جملة
 * الصيغة: [المستوى, الجملة مع ___, الترجمة, [الإجابة الصحيحة, خطأ, خطأ], الشرح]
 * ⚠️ اكتب الإجابة الصحيحة دائماً أولاً — القالب يخلط ترتيب الخيارات تلقائياً.
 * المستويات: easy (إحماء) | trap (فخاخ شائعة) | pro (أيديومز للمحترفين)
 */
window.QUIZ_QUESTIONS = [
  /* ==================== EASY: إحماء سهل ==================== */
  ['easy', 'She ___ coffee every morning.', 'هي تشرب القهوة كل صباح', ['drinks', 'drink', 'drinking'], 'مع He/She/It في المضارع البسيط نضيف s للفعل.'],
  ['easy', 'They ___ waiting for the bus.', 'هم ينتظرون الحافلة', ['are', 'is', 'am'], 'الضمير They يأخذ are دائماً.'],
  ['easy', 'I ___ a student.', 'أنا طالب', ['am', 'is', 'are'], 'الضمير I يأخذ am فقط.'],
  ['easy', 'He ___ to school yesterday.', 'ذهب إلى المدرسة أمس', ['went', 'goes', 'go'], 'yesterday = ماضٍ، وماضي go هو went.'],
  ['easy', 'There ___ many people here.', 'يوجد الكثير من الناس هنا', ['are', 'is', 'was'], 'people جمع، لذلك نقول there are.'],
  ['easy', 'I have ___ apple.', 'عندي تفاحة', ['an', 'a', 'the'], 'قبل الصوت المتحرك (a, e, i, o, u) نستخدم an.'],
  ['easy', 'My birthday is ___ May.', 'عيد ميلادي في شهر مايو', ['in', 'on', 'at'], 'مع الشهور نستخدم in.'],
  ['easy', 'See you ___ Monday!', 'أراك يوم الاثنين', ['on', 'in', 'at'], 'مع أيام الأسبوع نستخدم on.'],
  ['easy', 'The meeting is ___ 5 o\'clock.', 'الاجتماع الساعة الخامسة', ['at', 'in', 'on'], 'مع الساعة المحددة نستخدم at.'],
  ['easy', 'I am very ___. I need to sleep.', 'أنا متعب جداً، أحتاج للنوم', ['tired', 'hungry', 'angry'], 'tired = متعب.'],
  ['easy', 'Can you ___ me, please?', 'هل يمكنك مساعدتي من فضلك؟', ['help', 'helps', 'helping'], 'بعد can يأتي الفعل مجرداً بدون s أو ing.'],
  ['easy', 'We ___ football every Friday.', 'نلعب كرة القدم كل جمعة', ['play', 'plays', 'playing'], 'We تأخذ الفعل بدون s.'],
  ['easy', 'This is ___ book.', 'هذا كتابي', ['my', 'me', 'I'], 'my للملكية وتأتي قبل الاسم.'],
  ['easy', '___ are you from?', 'من أين أنت؟', ['Where', 'What', 'Who'], 'Where = أين.'],
  ['easy', 'How ___ is this phone?', 'كم سعر هذا الهاتف؟', ['much', 'many', 'long'], 'للسؤال عن السعر نقول How much.'],
  ['easy', 'I don\'t have ___ money.', 'ليس لدي أي مال', ['any', 'some', 'many'], 'في النفي نستخدم any، وmoney غير معدود فلا يأخذ many.'],
  ['easy', 'She can ___ three languages.', 'تستطيع تحدث ثلاث لغات', ['speak', 'speaks', 'speaking'], 'بعد can الفعل يأتي مجرداً.'],
  ['easy', 'The opposite of "cheap" is ___.', 'عكس كلمة "رخيص" هو...', ['expensive', 'poor', 'small'], 'expensive = غالي الثمن.'],
  ['easy', 'I ___ TV right now.', 'أنا أشاهد التلفاز الآن', ['am watching', 'watch', 'watched'], 'right now تعني الحاضر المستمر: am + ing.'],
  ['easy', 'He ___ like spicy food.', 'هو لا يحب الأكل الحار', ['doesn\'t', 'don\'t', 'isn\'t'], 'He/She/It في النفي تأخذ doesn\'t.'],
  ['easy', '___ you like tea?', 'هل تحب الشاي؟', ['Do', 'Does', 'Are'], 'مع you نسأل بـ Do.'],
  ['easy', 'My sister is ___ than me.', 'أختي أطول مني', ['taller', 'tallest', 'more tall'], 'للمقارنة بين اثنين نضيف er ثم than.'],
  ['easy', 'It is the ___ day of my life!', 'إنه أفضل يوم في حياتي', ['best', 'better', 'good'], 'التفضيل المطلق لكلمة good هو the best.'],
  ['easy', 'I was born ___ 1998.', 'ولدت عام 1998', ['in', 'on', 'at'], 'مع السنوات نستخدم in.'],
  ['easy', 'Please ___ the door.', 'من فضلك أغلق الباب', ['close', 'closes', 'closing'], 'صيغة الأمر تأتي بالفعل المجرد.'],
  ['easy', 'There isn\'t ___ milk in the fridge.', 'لا يوجد حليب في الثلاجة', ['any', 'many', 'a'], 'milk غير معدود ومع النفي نستخدم any.'],
  ['easy', 'He has two ___.', 'لديه طفلان', ['children', 'childs', 'childrens'], 'جمع child شاذ: children.'],
  ['easy', 'I usually wake up early ___ the morning.', 'أستيقظ عادة مبكراً في الصباح', ['in', 'on', 'at'], 'نقول in the morning لكن at night.'],
  ['easy', 'Where ___ you yesterday?', 'أين كنت أمس؟', ['were', 'was', 'are'], 'you في الماضي تأخذ were.'],
  ['easy', 'I ___ English every day.', 'أدرس الإنجليزية كل يوم', ['study', 'studies', 'studying'], 'مع I لا نضيف s للفعل.'],

  /* ==================== TRAP: فخاخ وأخطاء شائعة ==================== */
  ['trap', 'I am married ___ a doctor.', 'أنا متزوج من طبيبة', ['to', 'with', 'from'], 'فخ مشهور! نقول married TO وليس married with.'],
  ['trap', 'She congratulated me ___ my success.', 'هنأتني على نجاحي', ['on', 'for', 'about'], 'congratulate someone ON something.'],
  ['trap', 'I\'m looking forward to ___ you.', 'أتطلع لرؤيتك', ['seeing', 'see', 'saw'], 'رغم وجود to، بعد look forward to يأتي الفعل + ing.'],
  ['trap', 'It depends ___ the weather.', 'الأمر يعتمد على الطقس', ['on', 'of', 'from'], 'نقول دائماً depend ON.'],
  ['trap', 'Ahmed is good ___ English.', 'أحمد جيد في الإنجليزية', ['at', 'in', 'with'], 'للمهارة نقول good AT وليس good in.'],
  ['trap', 'Listen ___ me carefully.', 'استمع إليّ جيداً', ['to', 'at', 'for'], 'listen TO someone.'],
  ['trap', 'She is ___ university student.', 'هي طالبة جامعية', ['a', 'an', 'the'], 'university تبدأ بصوت "يو" الساكن، لذلك a وليس an.'],
  ['trap', 'He is ___ honest man.', 'هو رجل أمين', ['an', 'a', 'the'], 'حرف h صامت في honest، فنبدأ بصوت متحرك ونستخدم an.'],
  ['trap', 'I agree ___ you.', 'أتفق معك', ['with', 'to', 'on'], 'agree WITH someone.'],
  ['trap', 'We arrived ___ the airport at 6.', 'وصلنا إلى المطار الساعة 6', ['at', 'to', 'on'], 'arrive AT مكان محدد، وarrive IN مدينة. لا نقول arrive to.'],
  ['trap', 'I\'m interested ___ learning English.', 'أنا مهتم بتعلم الإنجليزية', ['in', 'on', 'at'], 'interested IN.'],
  ['trap', 'She is afraid ___ dogs.', 'هي تخاف من الكلاب', ['of', 'from', 'at'], 'afraid OF وليس from (ترجمة حرفية من العربية).'],
  ['trap', 'Thank you ___ your help.', 'شكراً لمساعدتك', ['for', 'on', 'about'], 'thank you FOR something.'],
  ['trap', 'I\'m responsible ___ this project.', 'أنا مسؤول عن هذا المشروع', ['for', 'of', 'on'], 'responsible FOR.'],
  ['trap', 'He apologized ___ being late.', 'اعتذر عن التأخير', ['for', 'on', 'about'], 'apologize FOR something.'],
  ['trap', 'I have lived here ___ 2015.', 'أعيش هنا منذ 2015', ['since', 'for', 'from'], 'since مع نقطة بداية زمنية، وfor مع مدة.'],
  ['trap', 'I have lived here ___ five years.', 'أعيش هنا منذ خمس سنوات', ['for', 'since', 'from'], 'five years مدة زمنية، لذلك نستخدم for.'],
  ['trap', 'She told ___ the truth.', 'أخبرتني الحقيقة', ['me', 'to me', 'for me'], 'tell يأخذ الشخص مباشرة: told me. أما say فنقول said to me.'],
  ['trap', 'He ___ that he was busy.', 'قال إنه مشغول', ['said', 'told', 'spoke'], 'told تحتاج شخصاً بعدها (told me)، أما said فلا.'],
  ['trap', 'I need some ___ about the trip.', 'أحتاج بعض المعلومات عن الرحلة', ['information', 'informations', 'an information'], 'information غير معدودة: لا تُجمع ولا تأخذ an.'],
  ['trap', 'Can you give me some ___?', 'هل تعطيني بعض النصائح؟', ['advice', 'advices', 'an advice'], 'advice غير معدودة، نقول some advice أو a piece of advice.'],
  ['trap', 'I\'m not used to ___ up early.', 'لست معتاداً على الاستيقاظ مبكراً', ['getting', 'get', 'got'], 'be used to + فعل ing.'],
  ['trap', 'I ___ smoke, but I quit.', 'كنت أدخن لكني توقفت', ['used to', 'use to', 'am used to'], 'used to + فعل مجرد = عادة في الماضي انتهت.'],
  ['trap', 'If I ___ rich, I would travel the world.', 'لو كنت غنياً لسافرت حول العالم', ['were', 'am', 'will be'], 'في الشرط الثاني نستخدم were مع كل الضمائر.'],
  ['trap', 'The news ___ good today.', 'الأخبار جيدة اليوم', ['is', 'are', 'were'], 'news مفردة رغم حرف s في آخرها.'],
  ['trap', 'Everyone ___ here.', 'الجميع هنا', ['is', 'are', 'were'], 'everyone تعامل كمفرد: everyone is.'],
  ['trap', 'This decision will ___ everyone.', 'هذا القرار سيؤثر على الجميع', ['affect', 'effect', 'effort'], 'affect فعل (يؤثر)، effect اسم (التأثير).'],
  ['trap', 'Smoking has a bad ___ on health.', 'للتدخين تأثير سيئ على الصحة', ['effect', 'affect', 'effort'], 'بعد a نحتاج اسماً: effect = التأثير.'],
  ['trap', '___ going to be late!', 'سوف يتأخرون!', ['They\'re', 'Their', 'There'], 'They\'re اختصار They are.'],
  ['trap', 'Let\'s meet at ___ house.', 'لنلتقِ في منزلهم', ['their', 'there', 'they\'re'], 'their للملكية (الخاص بهم).'],
  ['trap', 'The dog wagged ___ tail.', 'هز الكلب ذيله', ['its', 'it\'s', 'it is'], 'its للملكية بدون فاصلة. it\'s = it is.'],
  ['trap', 'I ___ him yesterday.', 'رأيته أمس', ['saw', 'have seen', 'see'], 'مع yesterday (وقت منتهٍ) نستخدم الماضي البسيط وليس have seen.'],
  ['trap', 'Let\'s discuss ___ problem.', 'لنناقش المشكلة', ['the', 'about the', 'on the'], 'discuss لا يأخذ حرف جر. لا نقول discuss about.'],
  ['trap', 'Can you explain it ___?', 'هل تشرحه لي؟', ['to me', 'me', 'for me'], 'explain TO someone. لا نقول explain me.'],
  ['trap', 'She is ___ young to drive.', 'هي صغيرة جداً على القيادة', ['too', 'very', 'so'], 'too + صفة + to = أكثر من اللازم لفعل شيء.'],
  ['trap', 'The movie was so ___!', 'كان الفيلم ممتعاً جداً!', ['interesting', 'interested', 'interest'], 'ing لما يسبب الشعور، ed لمن يشعر.'],
  ['trap', 'I was ___ during the movie.', 'شعرت بالملل أثناء الفيلم', ['bored', 'boring', 'bore'], 'الشخص الذي يشعر بالملل = bored. الفيلم نفسه boring.'],
  ['trap', 'I prefer tea ___ coffee.', 'أفضّل الشاي على القهوة', ['to', 'than', 'from'], 'prefer X TO Y وليس than.'],
  ['trap', 'He is very different ___ his brother.', 'هو مختلف جداً عن أخيه', ['from', 'of', 'with'], 'different FROM.'],
  ['trap', 'Wait ___ me here!', 'انتظرني هنا!', ['for', 'to', 'at'], 'wait FOR someone.'],
  ['trap', 'She insisted ___ paying the bill.', 'أصرّت على دفع الفاتورة', ['on', 'to', 'for'], 'insist ON + ing.'],
  ['trap', 'I\'m looking ___ my keys.', 'أبحث عن مفاتيحي', ['for', 'at', 'to'], 'look for = يبحث عن، look at = ينظر إلى.'],
  ['trap', 'He spends a lot of money ___ clothes.', 'ينفق الكثير من المال على الملابس', ['on', 'in', 'for'], 'spend money ON something.'],
  ['trap', 'I\'m angry ___ him.', 'أنا غاضب منه', ['with', 'from', 'on'], 'angry WITH someone وليس from.'],
  ['trap', 'We went there ___ foot.', 'ذهبنا إلى هناك مشياً', ['on', 'by', 'with'], 'نقول on foot لكن by car.'],
  ['trap', 'We went there ___ car.', 'ذهبنا إلى هناك بالسيارة', ['by', 'on', 'with'], 'وسائل النقل: by car, by bus, by plane.'],
  ['trap', 'Hurry up! We have very ___ time.', 'أسرع! لدينا وقت قليل جداً', ['little', 'few', 'many'], 'time غير معدود، لذلك little وليس few.'],
  ['trap', 'How ___ people came to the party?', 'كم شخصاً حضر الحفلة؟', ['many', 'much', 'lot'], 'people معدود، لذلك How many.'],
  ['trap', 'She has worked here ___ ten years.', 'تعمل هنا منذ عشر سنوات', ['for', 'since', 'during'], 'مع المدة الزمنية نستخدم for.'],
  ['trap', 'I ___ my keys. I can\'t find them!', 'أضعت مفاتيحي، لا أجدها!', ['have lost', 'lost already', 'am losing'], 'present perfect لحدث ماضٍ أثره مستمر الآن.'],
  ['trap', 'He made me ___.', 'جعلني أضحك', ['laugh', 'to laugh', 'laughing'], 'make someone + فعل مجرد بدون to.'],
  ['trap', 'Let me ___ you.', 'دعني أساعدك', ['help', 'to help', 'helping'], 'let someone + فعل مجرد بدون to.'],
  ['trap', 'I enjoy ___ books.', 'أستمتع بقراءة الكتب', ['reading', 'to read', 'read'], 'enjoy يتبعه الفعل + ing دائماً.'],
  ['trap', 'I want ___ a doctor.', 'أريد أن أصبح طبيباً', ['to become', 'becoming', 'become'], 'want + to + فعل.'],
  ['trap', 'The police ___ coming.', 'الشرطة قادمة', ['are', 'is', 'was'], 'police تعامل كجمع: the police are.'],
  ['trap', 'This is the man ___ helped me.', 'هذا الرجل الذي ساعدني', ['who', 'which', 'whose'], 'who للأشخاص وwhich للأشياء.'],
  ['trap', 'She ___ the piano since she was six.', 'تعزف البيانو منذ كانت في السادسة', ['has played', 'plays', 'played'], 'since مع حدث مستمر حتى الآن = present perfect.'],
  ['trap', 'I am ___ English teacher.', 'أنا معلم لغة إنجليزية', ['an', 'a', 'the'], 'English تبدأ بصوت متحرك، فنستخدم an.'],
  ['trap', 'Turn ___ the lights, please.', 'أطفئ الأنوار من فضلك', ['off', 'out', 'down'], 'turn off = يطفئ، turn on = يشغّل.'],
  ['trap', 'Please fill ___ this form.', 'من فضلك املأ هذا النموذج', ['in', 'on', 'at'], 'fill in (أو fill out) a form = يملأ نموذجاً.'],

  /* ==================== PRO: أيديومز للمحترفين ==================== */
  ['pro', 'Good luck! Break a ___!', 'حظاً موفقاً!', ['leg', 'arm', 'hand'], 'Break a leg تعبير شهير لتمني الحظ.'],
  ['pro', 'That car costs an arm and a ___.', 'تلك السيارة غالية جداً', ['leg', 'foot', 'head'], 'costs an arm and a leg = باهظ الثمن جداً.'],
  ['pro', 'I see him once in a ___ moon.', 'أراه نادراً جداً', ['blue', 'red', 'golden'], 'once in a blue moon = نادراً جداً.'],
  ['pro', 'The exam was a piece of ___.', 'كان الامتحان سهلاً جداً', ['cake', 'pie', 'bread'], 'a piece of cake = سهل جداً.'],
  ['pro', 'It\'s raining cats and ___!', 'إنها تمطر بغزارة!', ['dogs', 'birds', 'mice'], 'raining cats and dogs = مطر غزير جداً.'],
  ['pro', 'I\'m tired. Let\'s call it a ___.', 'أنا متعب، لننهِ العمل لهذا اليوم', ['day', 'night', 'time'], 'call it a day = ننهي العمل لليوم.'],
  ['pro', 'Don\'t beat around the ___.', 'لا تراوغ، ادخل في الموضوع', ['bush', 'tree', 'house'], 'beat around the bush = يراوغ ولا يصل للنقطة.'],
  ['pro', 'I\'m feeling under the ___.', 'أشعر بتوعك', ['weather', 'sky', 'rain'], 'under the weather = مريض قليلاً.'],
  ['pro', 'You hit the ___ on the head!', 'أصبت تماماً!', ['nail', 'hammer', 'wall'], 'hit the nail on the head = أصاب الهدف تماماً.'],
  ['pro', 'Speak of the ___! Here he comes.', 'جبنا طاريه وجاء!', ['devil', 'angel', 'king'], 'speak of the devil = عند ظهور من كنا نتحدث عنه.'],
  ['pro', 'I did my part. The ball is in your ___.', 'قمت بدوري، القرار الآن بيدك', ['court', 'hand', 'field'], 'the ball is in your court = الدور عليك الآن.'],
  ['pro', 'He let the cat out of the ___.', 'أفشى السر', ['bag', 'box', 'house'], 'let the cat out of the bag = أفشى سراً.'],
  ['pro', 'It will hurt, but you must bite the ___.', 'سيؤلم، لكن عليك التحمّل', ['bullet', 'apple', 'stone'], 'bite the bullet = يواجه أمراً صعباً بشجاعة.'],
  ['pro', 'Kill two birds with one ___.', 'ضرب عصفورين بحجر', ['stone', 'shot', 'bullet'], 'نفس المثل العربي تماماً!'],
  ['pro', 'Every cloud has a silver ___.', 'في كل محنة منحة', ['lining', 'line', 'side'], 'silver lining = الجانب المشرق.'],
  ['pro', 'Actions speak louder than ___.', 'الأفعال أبلغ من الأقوال', ['words', 'voices', 'sounds'], 'الأفعال أهم من الكلام.'],
  ['pro', 'Better late than ___.', 'أن تأتي متأخراً خير من ألا تأتي', ['never', 'sorry', 'early'], 'انتبه: better safe than sorry مثل آخر مختلف!'],
  ['pro', 'Don\'t cry over spilled ___.', 'لا تبكِ على اللبن المسكوب', ['milk', 'water', 'tea'], 'لا فائدة من الحزن على ما فات.'],
  ['pro', 'The early bird catches the ___.', 'من يبكر ينل الفرصة', ['worm', 'fish', 'fly'], 'من يستيقظ مبكراً يسبق غيره.'],
  ['pro', 'I\'m exhausted. Time to hit the ___.', 'أنا منهك، حان وقت النوم', ['sack', 'floor', 'door'], 'hit the sack = يذهب للنوم.'],
  ['pro', 'Tell me everything, I\'m all ___!', 'أخبرني، كلي آذان صاغية!', ['ears', 'eyes', 'hands'], 'I\'m all ears = أستمع بكل انتباه.'],
  ['pro', 'She got the job! She\'s on cloud ___.', 'حصلت على الوظيفة! هي في قمة السعادة', ['nine', 'seven', 'ten'], 'on cloud nine = سعيد جداً.'],
  ['pro', 'He will clean his room? When pigs ___!', 'سينظف غرفته؟ مستحيل!', ['fly', 'swim', 'sing'], 'when pigs fly = لن يحدث أبداً.'],
  ['pro', 'Time ___ when you\'re having fun.', 'الوقت يمر بسرعة عندما تستمتع', ['flies', 'runs', 'goes'], 'time flies = الوقت يطير.'],
  ['pro', 'Keep training. No pain, no ___!', 'استمر بالتمرين، لا نجاح بدون تعب!', ['gain', 'game', 'pay'], 'no pain, no gain = لا مكسب بدون تعب.'],
  ['pro', 'Practice makes ___.', 'التمرين يصنع الإتقان', ['perfect', 'better', 'master'], 'بالممارسة تصل للإتقان.'],
  ['pro', 'Out of sight, out of ___.', 'بعيد عن العين بعيد عن القلب', ['mind', 'heart', 'eye'], 'بالإنجليزية mind وليس heart!'],
  ['pro', 'Relax, it\'s not rocket ___.', 'استرخِ، الأمر ليس معقداً', ['science', 'engineering', 'math'], 'it\'s not rocket science = ليس صعباً.'],
  ['pro', 'He loves chocolate. He has a sweet ___.', 'يحب الشوكولاتة، إنه يعشق الحلويات', ['tooth', 'mouth', 'heart'], 'a sweet tooth = محب للحلويات.'],
  ['pro', 'We don\'t have time. Cut to the ___.', 'ليس لدينا وقت، ادخل في الموضوع', ['chase', 'race', 'run'], 'cut to the chase = ادخل في صلب الموضوع مباشرة.'],
  ['pro', 'Good luck! I\'ll keep my fingers ___.', 'بالتوفيق! أتمنى لك الحظ', ['crossed', 'closed', 'together'], 'keep fingers crossed = أتمنى لك الحظ.'],
  ['pro', 'Starting a business? Easier said than ___.', 'بدء مشروع؟ الكلام أسهل من الفعل', ['done', 'made', 'finished'], 'easier said than done = قوله أسهل من فعله.'],
];
